export const languages = [
  { code: "en-US", name: "English" },
  { code: "zh-CN", name: "中文 (简体)" },
  { code: "es-ES", name: "Español" },
  { code: "es-MX", name: "Español (México)" },
  { code: "fr-FR", name: "Français" },
  { code: "de-DE", name: "Deutsch" },
  { code: "ar-AE", name: "العربية" },
  { code: "pt-BR", name: "Português" },
  { code: "ru-RU", name: "Русский" },
  { code: "ja-JP", name: "日本語" },
  { code: "ko-KR", name: "한국어" },
  { code: "vi-VN", name: "Tiếng Việt" },
  { code: "it-IT", name: "Italiano" },
  { code: "tr-TR", name: "Türkçe" },
  { code: "pl-PL", name: "Polski" },
  { code: "th-TH", name: "ไทย" },
  { code: "id-ID", name: "Bahasa Indonesia" },
];
